# Site settings
title: Assemble Austin
email: your-email@domain.com
description: > 
  Where people get together.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: aulali
github_username:  aulali
collections:
  tech:
    output: true
  arts:
    output: true
  food:
    output: true
  movement:
    output: true

# Build settings
markdown: kramdown
